name = "toddledemo"
compatibility_date = "2026-02-27"

[env.production]
vars = { ENVIRONMENT = "production" }

# Indique à Wrangler où trouver les dépendances des Fonctions
[build]
upload.format = "service-worker"

# Point crucial : cette section force l'inclusion du dossier
[site]
bucket = "./"
include = ["functions/**/*", "nordcraft-export-*.json"]
exclude = []
